const books = [
    {
      id: 1,
      title: "Cantik Itu Luka",
      author: "Eka Kurniawan",
      year: 2016,
      description: "Kisah dalam buku ini diawali oleh seorang perempuan yang bangkit dari kuburannya setelah dua puluh satu tahun kematiannya.",
      image: "https://www.gramedia.com/blog/content/images/2021/12/Cantik-itu-Luka-Cover-Besar.jpg",
    },
    {
      id: 2,
      title: "Laut Bercerita",
      author: "Leila S. Chudori",
      year: 2020,
      description: "Laut Bercerita mengisahkan arti keluarga yang kehilangan, sekumpulan sahabat yang merasakan kekosongan di dada, sekelompok orang yang gemar menyiksa dan lancar berkhianat, sejumlah keluarga yang mencari kejelasan makam anaknya, dan tentang cinta yang tak akan luntur oleh waktu.",
      image: "https://www.gramedia.com/blog/content/images/2022/01/Laut-Bercerita4-1.jpg",
    },
    {
      id: 3,
      title: "Bumi Manusia",
      author: "Pramoedya Ananta Toer",
      year: 2015,
      description: "Buku yang awalnya menceritakan pergerakan nasional, pertautan rasa, kegamangan jiwa, percintaan, dan pertarungan kekuatan para srikandi yang mengawal penyemaian bangunan nasional hingga melahirkan bangsa Indonesia modern ini, memiliki banyak adegan sentimentil yang ditulis oleh Pram. ",
      image: "https://www.gramedia.com/blog/content/images/2022/01/Bumi-Manusia-1.jpg",
    },
    {
      id: 4,
      title: "Saman",
      author: "Ayu Utami",
      year: 1998,
      description: "Dwilogi Saman dan Larung ini berawal dari kisah empat perempuan yang bersahabat sejak kecil, ada Shakuntala yang pemberontak, Cok yang nakal, Yasmin yang jaim, serta Laila yang lugu dan sedang bimbang apakah dirinya harus menyerahkan diri kepada lelaki yang telah beristri ataukah tidak.",
      image: "https://www.gramedia.com/blog/content/images/2022/01/9786024243999_Saman-2018.jpg",
    },
    {
      id: 5,
      title: "Ronggeng Dukuh Paruk ",
      author: "Ahmad Tohari",
      year: 2009,
      description: "Ronggeng Dukuh Paruk kisahkan penari ronggeng baru bernama Srintil, yang baru saja dinobatkan sebagai ronggeng terakhir setelah kematian 12 tahun ronggeng lamanya.",
      image: "https://www.gramedia.com/blog/content/images/2022/01/9789792201963_Ronggeng-Dukuh-Paruk.jpg",
    },
    {
      id: 6,
      title: "Entrok",
      author: "Okky Madasari",
      year: 2010 ,
      description: "Entrok merupakan novel yang kisahkan perempuan Jawa buta huruf bernama Marni dan anaknya yang bernama Rahayu. Dua orang yang terikat hubungan darah ini, seketika menjadi orang asing bagi satu sama lain selama bertahun-tahun lamanya. ",
      image: "https://www.gramedia.com/blog/content/images/2022/01/9786020652191_entrok_cu_cov.jpg",
    },
    {
      id: 7,
      title: "Sumur",
      author: "Eka Kurniawan",
      year: 2021,
      description: "Kisah kekeringan berkepanjangan di suatu kampung, membuat satu per satu orang meninggalkan kampung ini dan pindah ke tempat lain. ",
      image: "https://www.gramedia.com/blog/content/images/2022/01/9786020653242_SUMUR--1-.jpg",
    },
    {
      id: 8,
      title: "Laskar Pelangi",
      author: "Andrea Hirata",
      year: 2005,
      description: "Laskar Pelangi mengisahkan tentang sebelas anak yang berasal dari keluarga miskin, di mana mereka harus selalu berjuang dalam menempuh pendidikannya di sekolah sederhana yang ada di desa Balitong.",
      image: "https://www.gramedia.com/blog/content/images/2022/01/img212.jpg",
    },
    {
      id: 9,
      title: "Tenggelamnya Kapal Van Der Wijck",
      author: "Abdul Malik Karim Amrullah (Buya Hamka)",
      year: 2017,
      description: "Mengisahkan seorang pemuda berdarah Minang dan ayah yang berdarah bugis bernama Zainuddin, diawali dengan kisah ibu baik hati dan penuh harapan akan sambutan gembira, saat ia dan keluarga kecilnya kembali ke tanah kelahiran ayahnya di Padang Panjang, Mengkasar.",
      image: "https://www.gramedia.com/blog/content/images/2022/01/img067.jpg",
    },
];
  
export default books;